#
# Codec Schema
#

# Codec Name
name: Tokenized Message Types

# Unique Identifier
package: messages

# Codec Version
version: 1

# Register Supported Messages
messages:
  - "general/0002 - Public Message"
  - "general/0003 - Private Message"
  - "general/0004 - Reverted Tx"
  - "commercial/1001 - Offer"
  - "commercial/1002 - Signature Request"
  - "commercial/1003 - Settlement Request"
  - "commercial/1004 - Output Metadata"

# Register Field Types
fieldTypes:
  - "types/Output"
  - "types/OutputTag"
  - "types/Document"

# Define Field Aliases
fieldAliases:
