#
# Codec Schema
#

# Codec Name
name: Tokenized Message Types

# Unique Identifier
package: messages

# Codec Version
version: 1

# Register Supported Messages
messages:
  - "general/0002 - Public Message"
  - "general/0003 - Private Message"
  - "general/0004 - Reverted Tx"
  - "commercial/1001 - Offer"
  - "commercial/1002 - Signature Request"
  - "commercial/1003 - Settlement Request"
  - "commercial/1004 - Output Metadata"

# Register Resources
resources: []

# Register Field Types
fieldTypes:
  - "types/Output"
  - "types/OutputTag"
  - "types/Document"
  - "types/TargetAddress"

# Define Field Aliases
fieldAliases:
  - name: Tag
    type: uint
    size: 8
    resource: Tags

  - name: PublicKeyHash
    type: varbin
    size: 1

  - name: Timestamp
    type: uint
    size: 8

  - name: TxId
    type: bin
    size: 32
