#
# Codec Schema
#

# Codec Name
name: Tokenized Message Types

# Unique Identifier
code: messages

# Codec Version
version: 1

# Output Template
template: default

# Message ID
id:
    name: MessageCode
    type: uint
    size: 2

# Define Header Fields
headerFields:
  - name: Version
    label: Payload Version
    description: The version number that this asset payload adheres to.
    type: uint
    size: 8
    example: 1

  - name: MessageCode
    label: Message Code
    description: The Message Code that determines the expected contents of the message payload.
    type: uint
    size: 2
    example: 1001

# Register Supported Messages
messages:
  - "general/0002 - Public Message"
  - "general/0003 - Private Message"
  - "general/0004 - Reverted Tx"
  - "commercial/1001 - Offer"
  - "commercial/1002 - Signature Request"
  - "commercial/1003 - Settlement Request"
  - "commercial/1004 - Output Metadata"

# Register Field Types
fieldTypes:
  - "types/Output"
  - "types/OutputTag"
  - "types/Document"

# Define Field Aliases
fieldAliases:
