#
# Codec Schema
#

# Codec Name
name: Tokenized Asset Types

# Unique Identifier
package: assets

# Output Template
template: default

# Codec Version
version: 1

# Version type must be an unsigned integer type, but can vary in size.
# The type can not be changed between versions.
versionType:
    type: uint
    size: 1

# Message Code used to determine which type of message is encoded.
code:
    name: AssetType
    type: fixedchar
    size: 3

# Register Supported Messages
messages:
  - "identity/MEM - Membership"
  - "currency/CUR - Currency"
  - "security/SHC - Common Share"
  - "utility/COU - Coupon"
  - "utility/LOY - Loyalty Points"
  - "utility/TIC - Admission Ticket"

# Register Field Types
fieldTypes:
  - "types/AgeRestriction"

# Define Field Aliases
fieldAliases:
  - name: CurrencyType
    type: fixedchar
    size: 3
