#
# Codec Schema
#

# Codec Name
name: Tokenized Asset Types

# Unique Identifier
package: assets

# Codec Version
version: 1

# Register Supported Messages
messages:
  - "identity/MEM - Membership"
  - "currency/CUR - Currency"
  - "security/SHC - Common Share"
  - "utility/COU - Coupon"
  - "utility/LOY - Loyalty Points"
  - "utility/TIC - Admission Ticket"

# Register Resources
resources:
  - "../../resources/develop/Currencies"

# Register Field Types
fieldTypes:
  - "types/AgeRestriction"

# Define Field Aliases
fieldAliases:
  - name: CurrencyType
    type: fixedchar
    size: 3

  - name: Timestamp
    type: uint
    size: 8
