#
# Codec Schema
#

# Codec Name
name: Tokenized Protocol

# Unique Identifier
package: actions

# Output Template
template: default

# Codec Version
version: 1

# Message Code used to determine which type of message is encoded.
code:
    name: ActionCode
    type: fixedchar
    size: 2

# Register Supported Messages
messages:
  - "actions/C1 - Contract Offer"
  - "actions/C2 - Contract Formation"
  - "actions/C3 - Contract Amendment"
  - "actions/C4 - Static Contract Formation"
  - "actions/C5 - Contract Address Change"
  - "actions/A1 - Asset Definition"
  - "actions/A2 - Asset Creation"
  - "actions/A3 - Asset Modification"
  - "actions/T1 - Transfer"
  - "actions/T2 - Settlement"
  - "actions/G1 - Proposal"
  - "actions/G2 - Vote"
  - "actions/G3 - Ballot Cast"
  - "actions/G4 - Ballot Counted"
  - "actions/G5 - Result"
  - "actions/E1 - Order"
  - "actions/E2 - Freeze"
  - "actions/E3 - Thaw"
  - "actions/E4 - Confiscation"
  - "actions/E5 - Reconciliation"
  - "actions/R1 - Establishment"
  - "actions/R2 - Addition"
  - "actions/R3 - Alteration"
  - "actions/R4 - Removal"
  - "actions/M1 - Message"
  - "actions/M2 - Rejection"

# Register Field Types
fieldTypes:
  - "types/Administrator"
  - "types/Amendment"
  - "types/AssetReceiver"
  - "types/AssetSettlement"
  - "types/AssetTransfer"
  - "types/Document"
  - "types/Entity"
  - "types/Manager"
  - "types/Oracle"
  - "types/QuantityIndex"
  - "types/TargetAddress"
  - "types/VotingSystem"

# Define Field Aliases
fieldAliases:
  - name: Role
    type: uint
    size: 8

  - name: EntityType
    type: fixedchar
    size: 1

  - name: Polity
    type: fixedchar
    size: 3

  - name: RejectionCode
    type: uint
    size: 8

  - name: Tag
    type: uint
    size: 8

  - name: Address
    type: varbin
    size: 1

  - name: AssetCode
    type: bin
    size: 32
