#
# Codec Schema
#

# Codec Name
name: Tokenized Protocol

# Unique Identifier
package: actions

# Codec Version
version: 1

# Register Supported Messages
messages:
  - "actions/C1 - Contract Offer"
  - "actions/C2 - Contract Formation"
  - "actions/C3 - Contract Amendment"
  - "actions/C4 - Static Contract Formation"
  - "actions/C5 - Contract Address Change"
  - "actions/A1 - Asset Definition"
  - "actions/A2 - Asset Creation"
  - "actions/A3 - Asset Modification"
  - "actions/T1 - Transfer"
  - "actions/T2 - Settlement"
  - "actions/G1 - Proposal"
  - "actions/G2 - Vote"
  - "actions/G3 - Ballot Cast"
  - "actions/G4 - Ballot Counted"
  - "actions/G5 - Result"
  - "actions/E1 - Order"
  - "actions/E2 - Freeze"
  - "actions/E3 - Thaw"
  - "actions/E4 - Confiscation"
  - "actions/E5 - Reconciliation"
  - "actions/R1 - Establishment"
  - "actions/R2 - Addition"
  - "actions/R3 - Alteration"
  - "actions/R4 - Removal"
  - "actions/M1 - Message"
  - "actions/M2 - Rejection"

# Register Resources
resources:
  - "../../resources/develop/Entities"
  - "../../resources/develop/Polities"
  - "../../resources/develop/Roles"
  - "../../resources/develop/Rejections"
  - "../../resources/develop/Tags"

# Register Field Types
fieldTypes:
  - "types/Administrator"
  - "types/AdminIdentityCertificate"
  - "types/Amendment"
  - "types/AssetReceiver"
  - "types/AssetSettlement"
  - "types/AssetTransfer"
  - "types/Document"
  - "types/Entity"
  - "types/Manager"
  - "types/Oracle"
  - "types/QuantityIndex"
  - "types/ReferenceTransaction"
  - "types/Service"
  - "types/TargetAddress"
  - "types/VotingSystem"

# Define Field Aliases
fieldAliases:
  - name: Role
    type: uint
    size: 1
    resource: Roles
    description: "A role within an entity. (i.e. CEO, CFO)"
    example: 5

  - name: EntityType
    type: fixedchar
    size: 1
    resource: Entities
    description: "A type of entity. (i.e. Individual, Public Company)"
    example: "I"

  - name: Polity
    type: fixedchar
    size: 3
    resource: Polities
    example: GBR
    description: "Polities (eg. Countries/Nation-States (ISO-3166 Alpha-3)"

  - name: RejectionCode
    type: uint
    size: 1
    resource: Rejections
    description: "Codes returned in rejection messages when a request is not accepted."
    example: 10

  - name: Tag
    type: uint
    size: 1
    resource: Tags
    description: "Predefined tags for output metadata."
    example: 1

  - name: Address
    type: varbin
    varSize: small
    description: "A representation of a bitcoin address in raw format, with no check sum or encoding."
    example: "20f8d521553a2b0de0ceba82b70c5dd184c6cd2f43"

  - name: ContractCode
    type: bin
    size: 32
    description: "32 randomly generated bytes. Each Contract Code should be unique. The Contract ID will be human facing and will be the Contract Code, with a checksum, encoded in base58 and prefixed by 'CON'. Contract ID = CON + base58(ContractCode + checksum).  Eg. Contract ID = 'CON18RDoKK7Ed5zid2FkKVy7q3rULr4tgfjr4'"
    example: "260840c0b3d4dadb870cd34ffbfc47fed903fe7d94a7a5bab491fb728aebcc74"

  - name: AssetType
    type: fixedchar
    size: 3
    description: A code representing the type of asset and the structure of the payload.
    example: "CUR"

  - name: AssetCode
    type: bin
    size: 32
    description: "Represents a unique identifier for an asset/token."
    example: "0e6996402ea456156838652e3bd82c6c0986ef7925021d31f3d397bdcdd985fe"

  - name: Timestamp
    type: uint
    size: 8
    description: "Represents a time, encoded as a 64 bit unsigned integer representing the number of nanoseconds since the Unix epoch."
    example: 1594668650000000000

  - name: TxId
    type: bin
    size: 32
    description: "Represents a Bitcoin transaction ID, the double SHA256 hash of the serialized transaction."
    example: "9d1ef0b1201c1dec3c1eb1caf758a988205226173e988e7a04afb4ea9977f506"

  - name: PublicKey
    type: bin
    size: 33
    description: "Represents a compressed public key."
    example: "027fed903fe7d94a7a5bab491fb728aebcc74260840c0b3d4dadb870cd34ffbfc4"
